export const Brazilian = [
    'A vida trará coisas boas se tiver paciência.',
    'Demonstre amor e alegria em todas as oportunidades e verá que a paz nasce dentro de si.',
    'Não compense na ira o que lhe falta na razão.',
    'Defeitos e virtudes são apenas dois lados da mesma moeda.',
    'A maior de todas as torres começa no solo.',
    'Não há que ser forte. Há que ser flexível.',
    'Todos os dias organiza os seus cabelos, por que não faz o mesmo com o coração?',
    'Há três coisas que jamais voltam, a flecha lançada, a palavra dita e a oportunidade perdida.',
    'A juventude não é uma época da vida, é um estado de espírito.',
    'Podemos escolher o que semear, mas somos obrigados a colher o que plantamos.',
    'Dê toda a atenção à formação dos seus filhos, sobretudo com bons exemplos da sua própria vida.',
    'Siga os bons e aprenda com eles.',
    'Não importa o tamanho da montanha, ela não pode tapar o sol.',
    'O bom-senso vale mais do que muito conhecimento.',
    'Quem quer colher rosas tem de estar preparado para suportar os espinhos.',
    'São os nossos amigos que nos ensinam as mais valiosas lições.',
    'Aquele que se importa com o sentimento dos outros, não é um tolo.',
    'A adversidade é um espelho que reflete o verdadeiro eu.',
    'Lamentar aquilo que não temos é desperdiçar aquilo que já possuímos.',
    'Uma bela flor é incompleta sem as suas folhas.',
    'Sem o fogo do entusiasmo, não há o calor da vitória.',
    'O riso é a menor distância entre duas pessoas.',
    'Os defeitos são mais fortes quando o amor é fraco.',
    'Amizade e Amor são coisas que se unem num piscar de olhos.',
    'Surpreender e ser surpreendido é o segredo do amor.',
    'Faça pequenas coisas hoje e coisas maiores lhe serão confiadas amanhã.',
    'A paciência na adversidade é sinal de um coração sensível.',
    'A sorte favorece a mente bem preparada.',
    'A sua visão se tornará mais clara apenas quando conseguir olhar para dentro do seu coração.',
    'Quem olha para fora sonha, quem olha para dentro acorda.'
];

export const English = [
    'Life will bring good things if you have patience.',
    'Show love and joy in every opportunity and you will see that peace is born within you.',
    'Do not compensate in anger what you lack in reason.',
    'Defects and virtues are just two sides of the same coin.',
    'The tallest tower starts on the ground.',
    'You don\'t have to be strong. You have to be flexible.',
    'Every day you organize your hair, why not do the same with your heart?',
    'There are three things that never come back: the arrow shot, the spoken word, and the lost opportunity.',
    'Youth is not a time of life, it is a state of mind.',
    'We can choose what to sow, but we are obliged to reap what we plant.',
    'Give all attention to the education of your children, especially with good examples from your own life.',
    'Follow the good and learn from them.',
    'No matter the size of the mountain, it cannot block the sun.',
    'Common sense is worth more than a lot of knowledge.',
    'Whoever wants to pick roses must be prepared to endure thorns.',
    'It is our friends who teach us the most valuable lessons.',
    'One who cares about the feelings of others is not a fool.',
    'Adversity is a mirror that reflects the true self.',
    'Regretting what we don\'t have is wasting what we already possess.',
    'A beautiful flower is incomplete without its leaves.',
    'Without the fire of enthusiasm, there is no warmth of victory.',
    'Laughter is the shortest distance between two people.',
    'Defects are stronger when love is weak.',
    'Friendship and love are things that come together in the blink of an eye.',
    'To surprise and be surprised is the secret of love.',
    'Do small things today and bigger things will be entrusted to you tomorrow.',
    'Patience in adversity is a sign of a sensitive heart.',
    'Luck favors a well-prepared mind.',
    'Your vision will become clearer only when you can look inside your heart.',
    'Whoever looks outside dreams, whoever looks inside awakens.'
];

export const Spanish = [
    'La vida traerá cosas buenas si tienes paciencia.',
    'Muestra amor y alegría en cada oportunidad y verás que la paz nace dentro de ti.',
    'No compenses en ira lo que te falta en razón.',
    'Defectos y virtudes son solo dos caras de la misma moneda.',
    'La torre más alta comienza en el suelo.',
    'No tienes que ser fuerte. Tienes que ser flexible.',
    'Todos los días organizas tu cabello, ¿por qué no haces lo mismo con tu corazón?',
    'Hay tres cosas que nunca vuelven: la flecha lanzada, la palabra dicha y la oportunidad perdida.',
    'La juventud no es una época de la vida, es un estado mental.',
    'Podemos elegir qué sembrar, pero estamos obligados a cosechar lo que plantamos.',
    'Dedica toda la atención a la educación de tus hijos, especialmente con buenos ejemplos de tu propia vida.',
    'Sigue a los buenos y aprende de ellos.',
    'No importa el tamaño de la montaña, no puede tapar el sol.',
    'El sentido común vale más que mucho conocimiento.',
    'Quien quiera recoger rosas debe estar preparado para soportar espinas.',
    'Son nuestros amigos quienes nos enseñan las lecciones más valiosas.',
    'Quien se preocupa por los sentimientos de los demás no es un tonto.',
    'La adversidad es un espejo que refleja el verdadero yo.',
    'Lamentar lo que no tenemos es desperdiciar lo que ya poseemos.',
    'Una hermosa flor está incompleta sin sus hojas.',
    'Sin el fuego del entusiasmo, no hay calor de la victoria.',
    'La risa es la distancia más corta entre dos personas.',
    'Los defectos son más fuertes cuando el amor es débil.',
    'La amistad y el amor son cosas que se unen en un abrir y cerrar de ojos.',
    'Sorprender y ser sorprendido es el secreto del amor.',
    'Haz cosas pequeñas hoy y se te confiarán cosas más grandes mañana.',
    'La paciencia en la adversidad es señal de un corazón sensible.',
    'La suerte favorece a una mente bien preparada.',
    'Tu visión se volverá más clara solo cuando puedas mirar dentro de tu corazón.',
    'Quien mira hacia afuera sueña, quien mira hacia adentro despierta.'
];
